name: Dashboard CI
on: push
jobs:
  vitest-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Tests
        run: npx vitest
